-- ============================================================
-- GENERATED by src/lib/pricing-matrix.test.ts from src/lib/pricing.ts. DO NOT EDIT.
-- Paste after verify_079.sql. Every case: application_list_price() must equal calculatePricing().total.
-- ============================================================
do $$
declare v int;
begin
  v := public.application_list_price('vendor', 0, 0, 1, 0, 0, 0, '[]'::jsonb, false);
  if v <> 50000 then raise exception 'FAIL MATRIX: vendor single: got %, pricing.ts says 50000', v; end if;
  v := public.application_list_price('vendor', 0, 0, 1, 0, 1, 0, '[]'::jsonb, false);
  if v <> 60000 then raise exception 'FAIL MATRIX: vendor single + corner: got %, pricing.ts says 60000', v; end if;
  v := public.application_list_price('vendor', 0, 0, 1, 0, 0, 0, '[{"kind":"extra_chairs","qty":1,"term":null}]'::jsonb, false);
  if v <> 55000 then raise exception 'FAIL MATRIX: vendor single + extra chairs: got %, pricing.ts says 55000', v; end if;
  v := public.application_list_price('vendor', 0, 0, 0, 1, 0, 0, '[]'::jsonb, false);
  if v <> 80000 then raise exception 'FAIL MATRIX: vendor double: got %, pricing.ts says 80000', v; end if;
  v := public.application_list_price('vendor', 0, 0, 2, 0, 5, 0, '[]'::jsonb, false);
  if v <> 120000 then raise exception 'FAIL MATRIX: vendor 2 singles, corners over the booth count are clamped: got %, pricing.ts says 120000', v; end if;
  v := public.application_list_price('vendor', 0, 0, 1, 0, 0, 0, '[]'::jsonb, true);
  if v <> 35000 then raise exception 'FAIL MATRIX: vendor veteran: got %, pricing.ts says 35000', v; end if;
  v := public.application_list_price('vendor', 3, 0, 1, 0, 0, 5, '[]'::jsonb, false);
  if v <> 50000 then raise exception 'FAIL MATRIX: vendor ignores artist quantities: got %, pricing.ts says 50000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 1, '[]'::jsonb, false);
  if v <> 85000 then raise exception 'FAIL MATRIX: artist single, 1 artist: got %, pricing.ts says 85000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 2, '[]'::jsonb, false);
  if v <> 90000 then raise exception 'FAIL MATRIX: artist single, 2 artists: got %, pricing.ts says 90000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 9, '[]'::jsonb, false);
  if v <> 100000 then raise exception 'FAIL MATRIX: artist single, artists over the cap (4 per booth) are clamped: got %, pricing.ts says 100000', v; end if;
  v := public.application_list_price('artist', 0, 1, 0, 0, 1, 4, '[]'::jsonb, false);
  if v <> 150000 then raise exception 'FAIL MATRIX: artist double, 4 artists, corner: got %, pricing.ts says 150000', v; end if;
  v := public.application_list_price('artist', 1, 1, 0, 0, 2, 6, '[]'::jsonb, false);
  if v <> 250000 then raise exception 'FAIL MATRIX: artist single + double, 6 artists, 2 corners: got %, pricing.ts says 250000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 1, '[]'::jsonb, true);
  if v <> 70000 then raise exception 'FAIL MATRIX: artist veteran: got %, pricing.ts says 70000', v; end if;
  v := public.application_list_price('artist', 1, 0, 2, 1, 0, 1, '[]'::jsonb, false);
  if v <> 85000 then raise exception 'FAIL MATRIX: artist ignores vendor quantities: got %, pricing.ts says 85000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 1, '[{"kind":"extra_table","qty":2,"term":null}]'::jsonb, false);
  if v <> 95000 then raise exception 'FAIL MATRIX: add-on extra table x2: got %, pricing.ts says 95000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 1, '[{"kind":"tattoo_bed","qty":1,"term":"daily"}]'::jsonb, false);
  if v <> 90000 then raise exception 'FAIL MATRIX: add-on tattoo bed daily: got %, pricing.ts says 90000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 1, '[{"kind":"tattoo_bed","qty":2,"term":"weekend"}]'::jsonb, false);
  if v <> 115000 then raise exception 'FAIL MATRIX: add-on tattoo bed weekend x2: got %, pricing.ts says 115000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 1, '[{"kind":"arm_rest","qty":1,"term":"daily"},{"kind":"tattoo_light","qty":1,"term":"weekend"}]'::jsonb, false);
  if v <> 97000 then raise exception 'FAIL MATRIX: add-on arm rest daily + tattoo light weekend: got %, pricing.ts says 97000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 1, '[{"kind":"tattoo_bed","qty":1,"term":"weekly"}]'::jsonb, false);
  if v <> 85000 then raise exception 'FAIL MATRIX: add-on with an unpriced term is ignored: got %, pricing.ts says 85000', v; end if;
  v := public.application_list_price('artist', 1, 0, 0, 0, 0, 1, '[{"kind":"extra_chairs","qty":0,"term":null}]'::jsonb, false);
  if v <> 85000 then raise exception 'FAIL MATRIX: add-on qty 0 is ignored: got %, pricing.ts says 85000', v; end if;
  v := public.application_list_price('artist', 1, 1, 0, 0, 2, 8, '[{"kind":"extra_table","qty":1,"term":null},{"kind":"tattoo_bed","qty":1,"term":"weekend"},{"kind":"arm_rest","qty":2,"term":"daily"}]'::jsonb, true);
  if v <> 273000 then raise exception 'FAIL MATRIX: everything: artist single + double, 8 artists, 2 corners, add-ons, veteran: got %, pricing.ts says 273000', v; end if;
  v := public.application_list_price('artist', 0, 0, 0, 0, 3, 3, '[]'::jsonb, false);
  if v <> 0 then raise exception 'FAIL MATRIX: zero booths, everything else set: zero base, permits clamped to 0, corners 0: got %, pricing.ts says 0', v; end if;
  raise notice 'PASS MATRIX: application_list_price() equals calculatePricing() on 22 cases';
end $$;
